// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sip} from '../models';
import {main} from '../models';
import {modules} from '../models';

export function ActivateStreamSignalProfile(arg1:string):Promise<sip.ProfileActivationResponse>;

export function ActivateTideReaderProfile(arg1:string):Promise<sip.ProfileActivationResponse>;

export function ActivateTuberSwitchProfile(arg1:string):Promise<sip.ProfileActivationResponse>;

export function AnnounceStreamSignal():Promise<sip.AnnounceResponse>;

export function ClearModuleExecutablePath(arg1:string):Promise<Array<main.ModuleExecutableConfig>>;

export function ConfirmStreamSignalAnnouncement(arg1:string):Promise<sip.AnnounceResponse>;

export function EndStreamSignalStream():Promise<sip.EndStreamResponse>;

export function GetAutoStartManagedModules():Promise<boolean>;

export function GetModuleExecutableConfigs():Promise<Array<main.ModuleExecutableConfig>>;

export function GetModules():Promise<Array<modules.Module>>;

export function GetStreamSignalAnnounceStatus():Promise<sip.AnnounceStatusResponse>;

export function GetStreamSignalCurrentProfile():Promise<sip.CurrentProfileResponse>;

export function GetStreamSignalEndStreamStatus():Promise<sip.EndStreamStatusResponse>;

export function GetStreamSignalProfiles():Promise<sip.ProfilesResponse>;

export function GetTideReaderCurrentProfile():Promise<sip.CurrentProfileResponse>;

export function GetTideReaderOverlaySnapshot():Promise<main.TideReaderOverlaySnapshot>;

export function GetTideReaderProfiles():Promise<sip.ProfilesResponse>;

export function GetTuberSwitchCurrentProfile():Promise<sip.CurrentProfileResponse>;

export function GetTuberSwitchProfiles():Promise<sip.ProfilesResponse>;

export function OpenModule(arg1:string):Promise<Array<modules.Module>>;

export function PickModuleExecutablePath(arg1:string):Promise<string>;

export function RefreshModules():Promise<Array<modules.Module>>;

export function SetAutoStartManagedModules(arg1:boolean):Promise<boolean>;

export function SetModuleExecutablePath(arg1:string,arg2:string):Promise<Array<main.ModuleExecutableConfig>>;

export function StartModule(arg1:string):Promise<Array<modules.Module>>;
