// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateStreamSignalProfile(arg1) {
  return window['go']['main']['App']['ActivateStreamSignalProfile'](arg1);
}

export function ActivateTideReaderProfile(arg1) {
  return window['go']['main']['App']['ActivateTideReaderProfile'](arg1);
}

export function ActivateTuberSwitchProfile(arg1) {
  return window['go']['main']['App']['ActivateTuberSwitchProfile'](arg1);
}

export function AnnounceStreamSignal() {
  return window['go']['main']['App']['AnnounceStreamSignal']();
}

export function ClearModuleExecutablePath(arg1) {
  return window['go']['main']['App']['ClearModuleExecutablePath'](arg1);
}

export function ConfirmStreamSignalAnnouncement(arg1) {
  return window['go']['main']['App']['ConfirmStreamSignalAnnouncement'](arg1);
}

export function EndStreamSignalStream() {
  return window['go']['main']['App']['EndStreamSignalStream']();
}

export function GetAutoStartManagedModules() {
  return window['go']['main']['App']['GetAutoStartManagedModules']();
}

export function GetModuleExecutableConfigs() {
  return window['go']['main']['App']['GetModuleExecutableConfigs']();
}

export function GetModules() {
  return window['go']['main']['App']['GetModules']();
}

export function GetStreamSignalAnnounceStatus() {
  return window['go']['main']['App']['GetStreamSignalAnnounceStatus']();
}

export function GetStreamSignalCurrentProfile() {
  return window['go']['main']['App']['GetStreamSignalCurrentProfile']();
}

export function GetStreamSignalEndStreamStatus() {
  return window['go']['main']['App']['GetStreamSignalEndStreamStatus']();
}

export function GetStreamSignalProfiles() {
  return window['go']['main']['App']['GetStreamSignalProfiles']();
}

export function GetTideReaderCurrentProfile() {
  return window['go']['main']['App']['GetTideReaderCurrentProfile']();
}

export function GetTideReaderOverlaySnapshot() {
  return window['go']['main']['App']['GetTideReaderOverlaySnapshot']();
}

export function GetTideReaderProfiles() {
  return window['go']['main']['App']['GetTideReaderProfiles']();
}

export function GetTuberSwitchCurrentProfile() {
  return window['go']['main']['App']['GetTuberSwitchCurrentProfile']();
}

export function GetTuberSwitchProfiles() {
  return window['go']['main']['App']['GetTuberSwitchProfiles']();
}

export function OpenModule(arg1) {
  return window['go']['main']['App']['OpenModule'](arg1);
}

export function PickModuleExecutablePath(arg1) {
  return window['go']['main']['App']['PickModuleExecutablePath'](arg1);
}

export function RefreshModules() {
  return window['go']['main']['App']['RefreshModules']();
}

export function SetAutoStartManagedModules(arg1) {
  return window['go']['main']['App']['SetAutoStartManagedModules'](arg1);
}

export function SetModuleExecutablePath(arg1, arg2) {
  return window['go']['main']['App']['SetModuleExecutablePath'](arg1, arg2);
}

export function StartModule(arg1) {
  return window['go']['main']['App']['StartModule'](arg1);
}
